// Script to generate SHA-256 hashes for quiz answers
import CryptoJS from "crypto-js";

// Function to normalize input (same as in answerValidator.js)
const normalizeInput = (input) => {
  if (typeof input !== "string") {
    return "";
  }

  return input
    .toLowerCase() // Приведение к нижнему регистру
    .trim() // Удаление пробелов в начале и конце
    .replace(/\s+/g, " "); // Замена множественных пробелов на одинарные
};

// Function to generate hash
const generateHash = (answer) => {
  const normalized = normalizeInput(answer);
  return CryptoJS.SHA256(normalized).toString();
};

// Static answers that we know
const staticAnswers = {
  task2: "прозрачность",
  task3: "review/tech-lead",
  task4: "notes.txt",
  task5: "18%",
  task6: "git diff HEAD~1 HEAD",
  task8: "v1.0-sent",
};

console.log("Generated SHA-256 hashes for static answers:");
console.log("=".repeat(50));

Object.entries(staticAnswers).forEach(([task, answer]) => {
  const hash = generateHash(answer);
  console.log(`${task}: "${answer}" -> ${hash}`);
});

console.log("\nDynamic answers (will be generated by setup_repository.sh):");
console.log("task1: First commit hash");
console.log("task7: ACME commit hash");
console.log("task9: Commit count in main");
